language:      node_js
git:
  depth:       3
node_js:
  - "node"
install:       npm install //abdi
script:
  - npm test
  - gulp
cache:
  directories:
    - node_modules
notifications:
  email:       false
